from __future__ import annotations

from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected, CommandError
from sqlalchemy import Column, Integer, Table, create_engine, inspect, text

from taskmarshal.persistence.tables import Base


@pytest.fixture(autouse=True)
def isolated_migration_environment(monkeypatch: pytest.MonkeyPatch) -> None:
    # env.py otherwise overrides each test's temporary database with a developer URL.
    monkeypatch.delenv("DATABASE_URL", raising=False)


def test_migration_check_rejects_unapplied_revisions(tmp_path: Path) -> None:
    config = Config("alembic.ini")
    config.set_main_option("sqlalchemy.url", f"sqlite:///{tmp_path / 'behind.db'}")
    with pytest.raises(CommandError, match="not up to date"):
        command.check(config)


def test_migration_check_rejects_model_changes_without_a_revision(tmp_path: Path) -> None:
    config = Config("alembic.ini")
    config.set_main_option("sqlalchemy.url", f"sqlite:///{tmp_path / 'drift.db'}")
    command.upgrade(config, "head")
    future_table = Table("unmigrated_table", Base.metadata, Column("id", Integer, primary_key=True))
    try:
        with pytest.raises(AutogenerateDiffsDetected):
            command.check(config)
    finally:
        Base.metadata.remove(future_table)


def test_forward_and_rollback_migration_with_populated_database(tmp_path: Path) -> None:
    database = tmp_path / "migration.db"
    config = Config("alembic.ini")
    config.set_main_option("sqlalchemy.url", f"sqlite:///{database}")

    command.upgrade(config, "head")
    engine = create_engine(f"sqlite:///{database}")
    with engine.begin() as connection:
        connection.execute(
            text(
                "INSERT INTO projects (id, name, description) "
                "VALUES ('00000000-0000-0000-0000-000000000001', 'test', '')"
            )
        )
    assert "attempts" in inspect(engine).get_table_names()

    command.downgrade(config, "base")
    assert "projects" not in inspect(engine).get_table_names()
    engine.dispose()


def test_revision_is_independent_of_current_orm_metadata(tmp_path: Path) -> None:
    database = tmp_path / "deterministic.db"
    config = Config("alembic.ini")
    config.set_main_option("sqlalchemy.url", f"sqlite:///{database}")
    future_table = Table(
        "future_model_table",
        Base.metadata,
        Column("id", Integer, primary_key=True),
    )
    engine = create_engine(f"sqlite:///{database}")
    try:
        command.upgrade(config, "head")
        assert "future_model_table" not in inspect(engine).get_table_names()

        future_table.create(engine)
        command.downgrade(config, "base")
        assert "future_model_table" in inspect(engine).get_table_names()
    finally:
        Base.metadata.remove(future_table)
        engine.dispose()
