from __future__ import annotations

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected, CommandError
from sqlalchemy import Column, Integer, MetaData, Table, inspect, select, update
from sqlalchemy.engine import Engine
from sqlalchemy.orm import Session
from tests.factories import seed_chain

from taskmarshal.persistence.database import make_engine
from taskmarshal.persistence.tables import Attempt, Base, Task


def test_migration_check_rejects_unapplied_revisions(migration_config: Config) -> None:
    with pytest.raises(CommandError, match="not up to date"):
        command.check(migration_config)


def test_migration_check_rejects_model_changes_without_a_revision(migration_config: Config) -> None:
    command.upgrade(migration_config, "head")
    future_table = Table("unmigrated_table", Base.metadata, Column("id", Integer, primary_key=True))
    try:
        with pytest.raises(AutogenerateDiffsDetected):
            command.check(migration_config)
    finally:
        Base.metadata.remove(future_table)


def snapshot(engine: Engine) -> dict[str, list[dict[str, object]]]:
    contents = {}
    with engine.connect() as connection:
        for name in sorted(inspect(connection).get_table_names()):
            if name == "alembic_version":
                continue
            table = Table(name, MetaData(), autoload_with=connection, resolve_fks=False)
            contents[name] = [
                dict(row)
                for row in connection.execute(select(table).order_by(table.c.id)).mappings()
            ]
    return contents


def without_configuration_names(
    contents: dict[str, list[dict[str, object]]],
) -> dict[str, list[dict[str, object]]]:
    projected = {table: [dict(row) for row in rows] for table, rows in contents.items()}
    for row in projected.get("agent_configurations", []):
        row.pop("name", None)
    return projected


@pytest.mark.parametrize("populated", [False, True], ids=["empty", "full-chain"])
def test_forward_and_rollback_preserve_existing_data(
    migration_config: Config, isolated_database_url: str, populated: bool
) -> None:
    command.upgrade(migration_config, "0001")
    engine = make_engine(isolated_database_url)
    try:
        if populated:
            with Session(engine) as session:
                seed_chain(session)
        original = snapshot(engine)
        command.upgrade(migration_config, "head")
        command.check(migration_config)
        upgraded = snapshot(engine)
        assert without_configuration_names(upgraded) == original
        if populated:
            assert {row["name"] for row in upgraded["agent_configurations"]} == {
                "Legacy configuration"
            }
        command.downgrade(migration_config, "0001")
        assert snapshot(engine) == original
        command.upgrade(migration_config, "head")
        command.check(migration_config)
        assert without_configuration_names(snapshot(engine)) == original
        command.downgrade(migration_config, "base")
        assert set(inspect(engine).get_table_names()) <= {"alembic_version"}
        command.upgrade(migration_config, "head")
        command.check(migration_config)
        assert all(not rows for rows in snapshot(engine).values())
    finally:
        engine.dispose()


@pytest.mark.parametrize("conflict", ["configuration", "input", "pointer", "epoch"])
def test_migration_rejects_existing_identity_conflicts_without_changing_data(
    migration_config: Config, isolated_database_url: str, conflict: str
) -> None:
    command.upgrade(migration_config, "0001")
    engine = make_engine(isolated_database_url)
    try:
        with Session(engine) as session:
            ids = seed_chain(session)
            if conflict == "pointer":
                session.execute(
                    update(Task)
                    .where(Task.id == ids["other_task"])
                    .values(current_specification_id=ids["specification"])
                )
            else:
                changes = {
                    "configuration": {"agent_configuration_id": ids["other_configuration"]},
                    "input": {"input_state_id": "b" * 64},
                    "epoch": {"ownership_epoch": 0},
                }
                session.execute(
                    update(Attempt).where(Attempt.id == ids["attempt"]).values(**changes[conflict])
                )
            session.commit()
        original = snapshot(engine)
        with pytest.raises(RuntimeError, match="^migration.identity_conflict$"):
            command.upgrade(migration_config, "head")
        assert snapshot(engine) == original
        with engine.connect() as connection:
            version = Table("alembic_version", MetaData(), autoload_with=connection)
            assert connection.scalar(select(version.c.version_num)) == "0001"
    finally:
        engine.dispose()


def test_revision_is_independent_of_current_orm_metadata(
    migration_config: Config, isolated_database_url: str
) -> None:
    future_table = Table(
        "future_model_table",
        Base.metadata,
        Column("id", Integer, primary_key=True),
    )
    engine = make_engine(isolated_database_url)
    try:
        command.upgrade(migration_config, "head")
        assert "future_model_table" not in inspect(engine).get_table_names()

        future_table.create(engine)
        command.downgrade(migration_config, "base")
        assert "future_model_table" in inspect(engine).get_table_names()
    finally:
        Base.metadata.remove(future_table)
        engine.dispose()
